Add configuration
AfricasVoices/Project-KE-Constitution-Review pull request #2
Opened 2021-08-09 13:28 UTC by DanielMwendwa

2021-08-11 14:42 UTC, IsaackMwenda requested changes

2021-08-11 14:42 UTC, IsaackMwenda commented on code_schemes/ws_correct_dataset.json
> +        {
This should contain all the ws codes in ke vax plus the new datasets for this project.

2021-08-11 14:42 UTC, IsaackMwenda commented on configurations/pipeline_config.json
> +  "BucketDirPath": "2021/KE-VAX"
```suggestion
  "BucketDirPath": "2021/KE-CONSTITUTION-REVIEW"
```

2021-08-11 14:42 UTC, IsaackMwenda commented on configurations/pipeline_config.json
> +        "gs://avf-project-datasets/2021/Kenya-Pool/worldvision_s01_demog.jsonl"
add gpsdd demog  datasets
"gs://avf-project-datasets/2021/Kenya-Pool/gpsdd_bungoma_s01_demog.jsonl",
"gs://avf-project-datasets/2021/Kenya-Pool/gpsdd_kilifi_s01_demog.jsonl",
"gs://avf-project-datasets/2021/Kenya-Pool/gpsdd_kiambu_s01_demog.jsonl"

2021-08-11 14:42 UTC, IsaackMwenda commented on configurations/pipeline_config.json
> +    {"RapidProKey": "avf_phone_id", "PipelineKey": "uid"},
add demog RapidProKeyRemappings reference engagement poll https://github.com/AfricasVoices/Project-KE-VAX/blob/main/configurations/engagement_poll_pipeline_config.json

2021-08-11 14:56 UTC, DanielMwendwa commented on configurations/pipeline_config.json
> +        "gs://avf-project-datasets/2021/Kenya-Pool/worldvision_s01_demog.jsonl"
updated, thanks.

2021-08-11 14:59 UTC, DanielMwendwa commented on configurations/pipeline_config.json
> +    {"RapidProKey": "avf_phone_id", "PipelineKey": "uid"},
Updated, thanks.

2021-08-12 06:45 UTC, IsaackMwenda commented on configurations/pipeline_config.json
> +    {"RapidProKey": "appointment_views (Text) - ke_constitution_review_poll", "PipelineKey": "appointment_views_raw", "IsActivationMessage": true},
```suggestion
    {"RapidProKey": "Appointment_Views (Text) - ke_constitution_review_poll", "PipelineKey": "appointment_views_raw", "IsActivationMessage": true},
```
The keys are usually Snake cased even though the variable names are not

2021-08-12 06:45 UTC, IsaackMwenda approved these changes
This looks good now thanks @DanielMwendwa

2021-08-12 07:07 UTC, merged